### ISSUE TITLE
Assignment 5.2 PY4E coursera

### ISSUE THREAD

**Issue by kratisinghai** [csev/py4e#232]
Hi,
 
I dont know why its taking maximum value as "bob" but not no.10

[Capture5](https://user-images.githubusercontent.com/59361512/72686564-23903d80-3b1c-11ea-8149-148956aba5ae.PNG)

![Capture5](https://user-images.githubusercontent.com/59361512/72686541-f80d5300-3b1b-11ea-96df-8ea568e89cbd.PNG)

**Comment by jemcghee3** [comment]
Hi I’m also learning, but it looks like you are not working the try/except to handle bob. It’s getting the except print statement, which you see, but then both the try and the except pass down further through the program because they have the same indention as try and except. Also, keep in mind a standard indention is four spaces in Python. Your varied indention is throwing off your program because that’s how python groups parts of the code together to figure out what to run next. 

Good luck!

**Comment by omicron-b** [comment]
Why do you think it does not convert 'bob' to int?

**Comment by srcatto** [comment]
Questions for assignments should not be asked here. Except for www.py4e.com, the other sites that host this course have discussion forum's, please use those.

**Comment by srcatto** [comment]
Please close this non-issue.
