### ISSUE TITLE
13.10, 15 - Twitter API no longer accessible with normal user account

### ISSUE THREAD

**Issue by Christina-Milner** [csev/py4e#289]
Chapter 13.10 states "To make use of these programs you will need to have a Twitter account, and authorize your Python code as an application, set up a key, secret, token and token secret.", and of course both chapters 13 and 15 rely on being able to do this at several points.

Having a standard Twitter account no longer gives access to this feature, one must apply for a developer account (https://developer.twitter.com/en/docs/twitter-api/getting-started/guide) and have their case approved. I didn't try and find out what happens with an use case of "I wanna run Dr. Chuck's Twitter spider", but in any case, the book is out of date in this regard.

**Comment by csev** [comment]
This has been a problem for a long time - ultimately this whole section needs to be rewritten not to use Twitter.

**Comment by Nakul-Dhingra** [comment]
### Please update the course

Please can you update that Twitter partly because I didn't find anything related to it on the internet? 
- Twitter thing is messed up and my humble request would be that if you can create that section again
- Also, Google has secured their API service with an API key
- Everything is so messed up that I even thought of quitting python but I finally found a way to speak to you

Thank you for such a wonderful course Dr Charles Severance and also for making it free. It would be great if you update these changes and make it the best course in the world out there 😄
@csev

**Comment by csev** [comment]
You are quite correct.  Twitter messed it all up.  That is a problem with a book that has real world examples.   The real world sometimes makes the examples not work.  One of these days I will make a whole new chapter, sample code, et c.  But for now, the book does cover how it worked at some point in the past and how talking APIs works in general.

**Comment by csev** [comment]
Hi all, as of January 2024, the book no longer mentions twitter *at all*.  Chapter 15 is now just a database chapter and all examples are twitter-free.  Let me know what you think.
