### ISSUE TITLE
Chapter 5 Iterations (how to iterate 100 times using the for loop)

### ISSUE THREAD

**Issue by zarehgorjian** [csev/py4e#340]
The chapter on loops presents no way one can use the for loop for a large number of iterations.

This can be done using the range() function.

This is worth mentioning in the Loops chapter.

People coming from other programming languages are looking for how to do a simple for loop.

for(i=0; i<100 ; i++){

}

the course should cover how to do the above for loop in Python, using the Python for loop.

**Comment by csev** [comment]
You make a great point.  But I don't cover this because this is a course specifically for beginners (not folks with lots of other languages).  So I keep things super simple.  If there is one way to describe things - that is what I talk about and stop there.  Range is not as bad as you think - if you use it in a simple loop - it does not generate a list of numbers at all - it creates an iterator / generator - which is as efficient as the loop you describe above.

**Comment by zarehgorjian** [comment]
OK, thank you. Coming to Python from Basic, Pascal, Fortran, C, C++ and Java, initially I found Python cryptic and hard to understand. I have no idea why they went with indentation when a simple "begin", "end" or "{" , "}" can make things so much simpler and far less error prone than using spaces vs. tabs etc.
